cost:
  # Weights
  linear_weight: 500.0
  angular_weight: 300.0
  regularization: 0
  vel_regularization: 0
  joint_limit_cost: 500.0
  reach_weight: 500.0            # Weight for reach cost

  # FR3 joint limits (rad)
  upper_limits: [2.8973, 1.7628, 2.8973, 3.0718, 2.8973, 3.7525, 2.8973]
  lower_limits: [-2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -3.7525, -2.8973]

  # Robot model parameters
  ee_frame: fr3_link8        # End-effector frame name
  arm_dof: 7                 # Number of arm joints taken from observation starting at index 3
  wheel_dof: 2               # Number of base/wheel DoF appended as zeros to match model nq

  max_reach: 0.8            # Maximum reach distance for the arm
  min_dist: 0.0             # Minimum distance to the target